### ISSUE TITLE
Error in CMakeFile.txt

### ISSUE THREAD

**Issue by JoostdeGussem** [HerveFrezza-Buet/RLlib#11]
When running: cmake . -DCMAKE_INSTALL_PREFIX=/usr,
the following error comes up. Do you know what is going wrong?

CMake Error at src/CMakeLists.txt:18 (install):
  install FILES given unknown argument

**Comment by jeremyfix** [comment]
Hi there,

First, you are not expected, as by convention, to run cmake from the source dir; 

So, I suggest you first to :  

```
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
...
```

Now, this may not explain your issue . Would you mind telling us which cmake version you are using ? Mine is 3.10.2.

**Comment by JoostdeGussem** [comment]
Hi Jeremy, running cmake from the build folder gives the same error. I am using a newer version of cmake, 3.17.2. Could that make a difference?

**Comment by JoostdeGussem** [comment]
I tried to do it over again, now it gives the error 
RLlib-master-2/src/rl-garnet.hpp:115:13: error: no member named 'random_shuffle' in namespace 'std'
              std::random_shuffle(next_states.begin(), next_states.end());

Is this an undefined function?

**Comment by HerveFrezza-Buet** [comment]
This method has been removed from C++17. I will update the code to fix this.
Sorry for the inconvenience.

**Comment by HerveFrezza-Buet** [comment]
I have done it. My g++ does not complain about this, even with the -std=c++17 flag. So I have not formally checked that the fix is ok. Please keep us posted.

**Comment by jeremyfix** [comment]
@JoostdeGussem I'm closing that issue since a fix has been found. If this is not the case, feel free to reopen.
